using System;
using System.Collections.Generic;

namespace DFM.Web.Models
{
    public class LoginRequest { public string Email { get; set; } public string Password { get; set; } }
    public class PasswordSetupRequest { public string Email { get; set; } public string Password { get; set; } public int SecurityQuestionId { get; set; } public string SecurityAnswer { get; set; } public string ResetToken { get; set; } }
    public class ResetChallengeRequest { public string Email { get; set; } public int SecurityQuestionId { get; set; } public string SecurityAnswer { get; set; } }
    public class AuthResult { public string Token { get; set; } public string Email { get; set; } public string DisplayName { get; set; } public string[] Roles { get; set; } public bool RequiresPasswordSetup { get; set; } }
    public class RoleAssignmentRequest { public int UserId { get; set; } public string[] Roles { get; set; } }
    public class ProjectRequest { public int? ProjectId { get; set; } public bool IsJira { get; set; } public string JiraKey { get; set; } public string ProjectName { get; set; } public string ProjectType { get; set; } public string AccountableExecLead { get; set; } public string AccountableExec { get; set; } public string SmeLead { get; set; } public string ProjectSize { get; set; } public string ProjectManager { get; set; } public string BudgetType { get; set; } public int? BudgetSourceId { get; set; } }
    public class PetRequest { public int? PetId { get; set; } public int ProjectId { get; set; } public string Code { get; set; } public decimal RequestedAmount { get; set; } public string Currency { get; set; } public string VendorName { get; set; } public List<SpendItemRequest> SpendItems { get; set; } }
    public class PetVendorRequest { public int? PetId { get; set; } public int ProjectId { get; set; } public string VendorName { get; set; } }
    public class SpendItemRequest { public int? SpendItemId { get; set; } public int PetId { get; set; } public string Head { get; set; } public string Topic { get; set; } public string Vendor { get; set; } public string CostType { get; set; } public string UnitType { get; set; } public decimal Units { get; set; } public decimal UnitPrice { get; set; } public string Currency { get; set; } public decimal ForeignAmount { get; set; } public decimal AedAmount { get; set; } public decimal ContingencyPercent { get; set; } public string GlNumber { get; set; } }
    public class DecisionRequest { public string Comments { get; set; } public bool Approve { get; set; } }
    public class BudgetLineRequest { public int? BudgetLineId { get; set; } public int PetId { get; set; } public string Vendor { get; set; } public string Justification { get; set; } public decimal Cost { get; set; } public string Currency { get; set; } public string GlNumber { get; set; } public string PetReference { get; set; } public string CamId { get; set; } public string CamStatus { get; set; } public DateTime? CamCreatedDate { get; set; } public DateTime? CamApprovedDate { get; set; } public string CamComments { get; set; } public string LpoRequest { get; set; } public DateTime? LpoIssueDate { get; set; } public string LpoComments { get; set; } }
    public class InvoiceRequest { public int? InvoiceId { get; set; } public int BudgetLineId { get; set; } public string VendorName { get; set; } public string Justification { get; set; } public string GlNumber { get; set; } public string InvoiceNumber { get; set; } public decimal InvoiceAmount { get; set; } public string InvoiceStatus { get; set; } public DateTime? PaymentDate { get; set; } }
}
